// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SpatialSearch")>]
[<assembly: AssemblyProductAttribute("SpatialSearch")>]
[<assembly: AssemblyDescriptionAttribute("An in memory tree for searching spatial data")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SpatialSearch"
    let [<Literal>] AssemblyProduct = "SpatialSearch"
    let [<Literal>] AssemblyDescription = "An in memory tree for searching spatial data"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
